task:
  name: Linux ARM64 Build
  arm_container:
    # image: ghcr.io/cirruslabs/ubuntu-runner-arm64:latest
    image: ubuntu:latest
  only_if: $CIRRUS_TAG != ''
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.3.1"
    DTLV_PLATFORM: linux
    DTLV_ARCH: aarch64
    GITHUB_TOKEN: ENCRYPTED[!792eb2fe7a2d61ddaed5c19202073ad6531db0f97953ecc815a24eb4f0d3772b95e59d4459ee5292639559a228f3e98f!]
  script: |

    curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod a+x lein
    sudo mv lein /usr/local/bin/

    lein run

    cd native
    script/install-graalvm

    export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-${GRAALVM_VERSION}/Contents/Home
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH

    script/compile

    cd ..
    native/dtlv-test0

    cd native

    sudo apt-get install -y p7zip-full

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-ubuntu-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
    chmod +x install
    sudo ./install

    bb --config ../.build/bb.edn release-artifact


task:
  name: macOS ARM64 Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  only_if: $CIRRUS_TAG != ''
  # only_if: "changesInclude('.cirrus.yml', 'src/*', 'native/script/*')"
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.3.1"
    DTLV_PLATFORM: macos
    DTLV_ARCH: aarch64
    GITHUB_TOKEN: ENCRYPTED[!792eb2fe7a2d61ddaed5c19202073ad6531db0f97953ecc815a24eb4f0d3772b95e59d4459ee5292639559a228f3e98f!]
  script: |

    brew install leiningen
    lein run

    cd native
    script/install-graalvm

    export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-${GRAALVM_VERSION}/Contents/Home
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH

    script/compile

    cd ..
    native/dtlv-test0

    cd native

    brew install p7zip

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-macos-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    brew install borkdude/brew/babashka

    bb --config ../.build/bb.edn release-artifact
