task:
  name: Linux ARM64 Build
  arm_container:
    # image: ghcr.io/cirruslabs/ubuntu-runner-arm64:latest
    image: ubuntu:latest
  only_if: $CIRRUS_TAG != ''
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.3.1"
    DTLV_PLATFORM: linux
    DTLV_ARCH: aarch64
    GITHUB_TOKEN: ENCRYPTED[4465a67af00336aee230128096c66806ff29a45ae7d46984ca6f7442505978661914be210ebc9d95cada71e23314706b]
  script: |

    apt-get update
    apt-get install -y curl git wget tar openjdk-11-jre-headless tree build-essential
    
    curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod a+x lein
    mv lein /usr/local/bin/

    export JAVA_OPTS="-Xmx8g -XX:+UseG1GC"
    lein run

    cd native
    script/install-graalvm

    export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-${GRAALVM_VERSION}
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH
    export STATIC_EXCEPT_LIBC=true

    tree ..
    script/compile

    cd ..
    native/dtlv-test0

    cd native

    apt-get install -y p7zip-full

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-ubuntu-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
    chmod +x install
    ./install

    bb --config ../.build/bb.edn release-artifact


task:
  name: macOS ARM64 Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  only_if: $CIRRUS_TAG != ''
  # only_if: "changesInclude('.cirrus.yml', 'src/*', 'native/script/*')"
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.3.1"
    DTLV_PLATFORM: macos
    DTLV_ARCH: aarch64
    GITHUB_TOKEN: ENCRYPTED[4465a67af00336aee230128096c66806ff29a45ae7d46984ca6f7442505978661914be210ebc9d95cada71e23314706b]
  script: |

    brew install leiningen
    lein run

    cd native
    script/install-graalvm

    export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-${GRAALVM_VERSION}/Contents/Home
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH

    script/compile

    cd ..
    native/dtlv-test0

    cd native

    brew install p7zip

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-macos-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    brew install borkdude/brew/babashka

    bb --config ../.build/bb.edn release-artifact
