#!/bin/bash

# compile on mac or aarch64 linux

set -eou pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

export USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=false
export DTLV_COMPILE_NATIVE=true

echo $JAVA_HOME

args_app=(
    "--verbose"
    "-jar" "target/main.uberjar.jar"
    "'-H:Name=dtlv'"
)

args_test0=(
    "--verbose"
    "-jar" "target/test0.uberjar.jar"
    "'-H:Name=dtlv-test0'"
)

if [ "$STATIC_EXCEPT_LIBC" = true ]; then
    args_app+=("'-H:+StaticExecutableWithDynamicLibC'")
    args_test0+=("'-H:+StaticExecutableWithDynamicLibC'")
fi

lein clean
lein with-profile native-uberjar uberjar

echo "ARGUMENTS $args_app"

"$GRAALVM_HOME/bin/native-image" "${args_app[@]}"

echo "DEBUG -----> 2"

lein clean
lein with-profile test0-uberjar uberjar

echo "DEBUG -----> 3"

"$GRAALVM_HOME/bin/native-image" "${args_test0[@]}"

echo "DEBUG -----> 4"
